apiVersion: v1
kind: Service
metadata:
    name: webshop-backend-service
    namespace: webshop-backend
spec:
    type: NodePort
    selector:
        app: webshop-backend
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          nodePort: 30001
