name: Go Test

on: 
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up GO
      uses: actions/setup-go@v5
      with: 
        go-version: '^1.23.6' 

    - name: Test
      run: go test -v ./...

    - name: build
      run: | 
          go build -o auth-main ./auth-service/cmd/main.go 
          go build -o product-main ./product-service/cmd/main.go 
          go build -o checkout-main ./checkout-service/cmd/main.go 
